name: VALIDANDO DOCKER

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Baixar imagem Docker
      run: docker pull guscarpim/docker-fiap:v1

    - name: Rodando o container
      run: docker run -d -p 3000:3000 guscarpim/docker-fiap:v1
